[project]
name = "setup-craw14ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bcrypt>=5.0.0",
    "crawl4ai",
    "fastapi[standard]>=0.141.1",
    "python-jose[cryptography]>=3.5.0",
]

[project.scripts]
setup-craw14ia = "src:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "src"
module-root = ""
